# Generated by Django 4.1.3 on 2022-11-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='username',
            field=models.CharField(default='yon', max_length=255),
            preserve_default=False,
        ),
    ]
