# Generated by Django 4.1.3 on 2022-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_product_images_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='artist-profile/images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArtistImage',
        ),
    ]
