# Generated by Django 4.1.3 on 2022-12-07 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0006_artist_profile_pic_delete_artistimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
