# Generated by Django 4.1.3 on 2022-12-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, upload_to='artist-profile/images'),
        ),
    ]
