# Generated by Django 4.1.3 on 2022-12-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_artist_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='artist-profile/images'),
        ),
    ]
