# Generated by Django 4.1.4 on 2022-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_artist_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
