# Generated by Django 4.1.4 on 2022-12-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_artist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_like', to='gallery.artist'),
        ),
    ]
