# Generated by Django 4.1.4 on 2022-12-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productbyartist', to='gallery.artist'),
        ),
    ]
