# Generated by Django 4.1.5 on 2023-01-31 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, default=None, null=True, upload_to='artist-profile/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='product/images')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productbyartist', to='gallery.artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.productcategory')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='product_like', to='gallery.artist')),
            ],
        ),
    ]
