# Generated by Django 4.1.3 on 2022-12-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
